#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2013-2017
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

include $(ALWAYS_COMPAT_MK)

-include $(GEN_CONFIG_MK)

ccflags-$(CONFIG_JAILHOUSE_GCOV) += -fprofile-arcs -ftest-coverage

objs-y += dbg-write.o lib.o psci.o control.o paging.o mmu_cell.o setup.o
objs-y += irqchip.o pci.o ivshmem.o uart-pl011.o uart-xuartps.o uart-mvebu.o
objs-y += uart-hscif.o uart-scifa.o uart-imx.o uart-imx-lpuart.o
objs-y += gic-v2.o gic-v3.o smccc.o

common-objs-y = $(addprefix ../arm-common/,$(objs-y))
