#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2013-2017
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

-include $(GEN_CONFIG_MK)

GCOV_PROFILE := n
ccflags-$(CONFIG_JAILHOUSE_GCOV) += -fprofile-arcs -ftest-coverage

OBJS-y += dbg-write.o lib.o psci.o control.o paging.o mmu_cell.o setup.o
OBJS-y += irqchip.o pci.o ivshmem.o uart-pl011.o uart-xuartps.o uart-mvebu.o
OBJS-y += uart-hscif.o
OBJS-y += gic-v2.o gic-v3.o

COMMON_OBJECTS = $(addprefix ../arm-common/,$(OBJS-y))
