#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2013-2016
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

include $(src)/../arm-common/Kbuild

KBUILD_AFLAGS := $(subst -include asm/unified.h,,$(KBUILD_AFLAGS))

always := built-in.o

obj-y := $(COMMON_OBJECTS)
obj-y += entry.o exception.o setup.o control.o traps.o mmio.o lib.o
obj-y += mmu_hyp.o caches.o mach-stubs.o

# in here we switch of the MMU and stuff, cant profile such code
# NOTE
#  gcc7 will bring a new function attribute "no_profile_instrument_function"
#  should switch to that for higher granularity, but gcc7 is not even there
CFLAGS_mmu_hyp.o += -fno-profile-arcs -fno-test-coverage

obj-$(CONFIG_MACH_VEXPRESS) += mach-vexpress.o
