#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2016
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

LINUXINCLUDE += -I$(src)/arch/arm-common/include

KBUILD_CFLAGS += -marm -march=armv7ve -msoft-float
KBUILD_AFLAGS += -march=armv7ve -msoft-float
