#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2013
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

always := built-in.o

obj-y := apic.o dbg-write.o entry.o setup.o fault.o vmx.o control.o mmio.o \
	 ../../acpi.o vtd.o

obj-y += nvmx.o
