#
# Jailhouse AArch64 support
#
# Copyright (C) 2015 Huawei Technologies Duesseldorf GmbH
# Copyright (c) Siemens AG, 2016
#
# Authors:
#  Antonios Motakis <antonios.motakis@huawei.com>
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

include $(src)/../arm-common/Kbuild

always := built-in.o

# units initialization order as defined by linking order:
# irqchip (common-objs-y), <generic units>

obj-y := $(common-objs-y)
obj-y += entry.o setup.o control.o mmio.o caches.o traps.o
