#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2013, 2014
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

KBUILD_CFLAGS += -m64 -mno-red-zone
GCOV_PROFILE := n

define DECLARE_TARGETS =
 _TARGETS = $(1)
 always := $$(_TARGETS)
 # $(NAME-y) NAME-linked.o NAME.bin
 targets += $$(foreach t,$$(_TARGETS:.bin=-y),$$($$t)) \
            $$(_TARGETS:.bin=-linked.o) $$(_TARGETS)
endef

# prevent deleting intermediate files which would cause rebuilds
.SECONDARY: $(addprefix $(obj)/,$(targets))

# obj/NAME-linked.o: ... obj/$(NAME-y) lib/lib[32].a
.SECONDEXPANSION:
$(obj)/%-linked.o: $(INMATES_LIB)/inmate.lds $$(addprefix $$(obj)/,$$($$*-y)) \
		   $(INMATES_LIB)/$$(if $$($$*_32),lib32.a,lib.a)
	$(call if_changed,ld)

$(obj)/%.bin: $(obj)/%-linked.o
	$(call if_changed,objcopy)

# 32-bit (i386) support
define DECLARE_32_BIT =
 CFLAGS_$(1).o := -m32
 LDFLAGS_$(1)-linked.o := /dev/null -m elf_i386 -T
 $(1)_32 := y
endef
